BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[Type] DROP CONSTRAINT [Type_Product_Id_fkey];

-- AddForeignKey
ALTER TABLE [dbo].[Type] ADD CONSTRAINT [Type_Product_Id_fkey] FOREIGN KEY ([Product_Id]) REFERENCES [dbo].[Product]([Product_Id]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
